#channels:
 # - anaconda
  #- conda-forge
  #- defaults
#dependencies:
    #- dlib
   # - cmake
    - numpy
    - scipy
    - tensorflow-cpu
    - streamlit
    - opencv-python-headless
    - pillow
    - pytube
    - matplotlib
    - ipython
