channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - pip:
        - tensorflow-cpu
        - streamlit
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
